<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>f4ddd7bb-f36f-487c-b972-7825212286ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a8b0c91-e56d-4089-9eff-9d0295476bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68113140-cbe9-4c66-83e7-ebb29455d6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106.0</value>
      <webElementGuid>bdc6ddb4-2aaa-4be4-a29e-0be3292280a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4e924838-3a5a-4fee-8279-b980730a7b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>0382b31a-f5f0-4f97-a059-5e2ad38a546e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>d5ba274d-cc60-47d5-9a1c-a44460b8bcab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>6764c64f-e40f-40d4-ac05-5c2a5411c9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>740.0</value>
      <webElementGuid>6b5dd12f-242f-425e-bb5f-713514aa60ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>44.0</value>
      <webElementGuid>b683f644-2dd1-44ce-b459-1a56663a9ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>822.0</value>
      <webElementGuid>35d972ab-191e-451b-b71c-6995ab0025c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>c3a4f782-d683-4b59-a89a-b6a74352082e</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</locator>
   <locatorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND value == 'Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'`]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Aktivasi dan verifikasi kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
