<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>66d33932-3bec-4a0f-88ab-fd61a5619610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc90cf0b-45af-4b99-af5b-3a296ab4e28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>332de7a8-dca8-48d8-8da4-015af0040321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106.0</value>
      <webElementGuid>454a1724-6991-435c-a241-cd8017957b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>be722893-c4a2-48b0-86b6-b3314dd67c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>765eb204-f341-4360-b2e4-058c04938335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>02f8dac0-d1ed-41cb-ac7d-ada6db70ce34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>0841b267-2916-4777-b02c-a8a45199e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>740.0</value>
      <webElementGuid>5f441641-1b89-4a95-99b0-3e13086121ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>44.0</value>
      <webElementGuid>07534683-8782-4cb3-885f-611a7a7ed713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>822.0</value>
      <webElementGuid>d76793fa-1a8e-4265-a3aa-eb0765e5f3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>09d5d12d-a3cb-4657-b866-17836ef79f11</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</locator>
   <locatorCollection>
      <entry>
         <key>NAME</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND value == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'`]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
