<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>07e0b00c-8aa0-4bcb-a41f-3a5a51d9aa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89e06415-9228-460f-930a-adf6671293d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fd9737ad-a111-4c62-b542-9b6a4b8b1a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>106.0</value>
      <webElementGuid>3295e3fb-8b58-4bbf-b641-910a6c51a4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b132bb04-2de9-4d3a-b695-1681dc671fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>058b34d0-e6d3-41da-827f-8fbe8a4e3e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>24729e4b-aa32-460c-a0f7-16dfda92202b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      <webElementGuid>141b50a1-63e4-4fc2-ac86-5e452ebe560f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>740.0</value>
      <webElementGuid>3e6eacaf-697f-41af-bb86-11f5fce23c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>44.0</value>
      <webElementGuid>904a063d-51c9-45ae-a6f1-cd09b292e94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>822.0</value>
      <webElementGuid>3866d0c7-edaa-412e-b72d-3c2c3c686b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      <webElementGuid>3471d4b4-e041-4e55-a73b-bbae04219f21</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</locator>
   <locatorCollection>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[2]</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @name = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' and @value = 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini']</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND name == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini' AND value == 'Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini'`]</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Pendaftaran kepesertaan Anda di BPJAMSOSTEK berhasil. Anda dapat mengakses semua fitur di aplikasi ini</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
