<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>8d99c1cb-a167-4c19-bba3-a2388db9af22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ed564dc-8f9d-4fd7-a700-12faa795ab7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ef1e953-d9d6-4224-b073-f092fb0aadf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86.0</value>
      <webElementGuid>a70524f4-7087-45d8-b5be-9b9efd9869a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0b793c3b-39f8-4eeb-a436-53cf23eb3dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      <webElementGuid>a535b263-5c92-46ea-bffb-9445365060aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      <webElementGuid>222cb7f4-f241-40ee-868d-6b320ffa8b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      <webElementGuid>4d084fa0-8f13-44ab-b216-7c09e86084f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>306.0</value>
      <webElementGuid>5083cb1b-6e40-4053-a607-7cb43f644977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>64.0</value>
      <webElementGuid>db5147a0-474f-4f00-94a9-39e02935957f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1192.0</value>
      <webElementGuid>eacbeef3-3bd4-4dd2-aecb-20618a53d761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>f937ed98-4cad-4b11-b173-fbfd32dbc334</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' and @name = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' and @value = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' and @name = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' and @value = 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan']</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' AND name == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' AND value == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' AND name == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan' AND name == 'Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan'</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Musisi Diharapkan Lebih Nyaman Berkarya, FESMI Kolaborasi dengan BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
