<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>2c00e09a-d55d-43f8-b224-ab742da3412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f495d392-6235-4a69-a240-44b8851f6a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f352de1-4cb6-4bbf-ac0d-bcfccd774887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86.0</value>
      <webElementGuid>551055a4-293a-43c6-b4a8-6bf6e35b5722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cf866bda-0cce-4e58-914d-17a3b3cfb727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      <webElementGuid>5521d7e4-29c6-41a7-9119-a919fff41f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      <webElementGuid>6e80cf20-07d5-4f7c-910e-282cca67228f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      <webElementGuid>36d5eae6-94b6-467b-9964-29ea1d688bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>306.0</value>
      <webElementGuid>1539af9c-0606-4d23-9dca-c0c37101aca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>64.0</value>
      <webElementGuid>5b38fb28-ba5a-4492-88b8-6800ad6a4f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1192.0</value>
      <webElementGuid>be4a6079-73f0-4829-b12d-bbcd499f228d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>a9ebb149-4ee5-4673-bb97-1e99d18202d4</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' and @name = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' and @value = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' and @name = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' and @value = 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024']</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' AND name == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' AND value == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' AND name == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024' AND name == 'BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024'</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>BPJS Ketenagakerjaan Ambil Bagian di Expo IKN 2024</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
