<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>ff34e21e-ad99-43d4-a2d6-6547f8eda660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b5cbf87-016d-4af8-bdee-45302825519a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3c5bbf4-0612-46b6-ab80-f27027b6a9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>88.0</value>
      <webElementGuid>0c474968-df98-43bc-8c3e-cd103cc0a410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e50f6c33-f529-4a50-8ec7-a1eae478234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      <webElementGuid>23f26325-1c0a-4603-950c-dea052e18e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      <webElementGuid>613a1260-1a69-4211-af30-2c5cd781f99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      <webElementGuid>1bf0a27d-a45e-437b-b74b-4e1f4329b2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>684.0</value>
      <webElementGuid>f148c224-576a-451c-8a18-d8cb70ec0f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>72.0</value>
      <webElementGuid>25f98e30-9135-4a64-9bd4-2100fa0fc05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>696.0</value>
      <webElementGuid>fd0c06a1-0157-4cdd-98d8-d24bcb15c434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>81410344-59c8-423a-9843-0a280bc96d82</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' and @name = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' and @value = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' and @name = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' and @value = 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja']</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' AND name == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' AND value == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' AND name == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja' AND name == 'BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja'</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>BPJS Ketenagakerjaan, Bank BJB dan REI Bersinergi Sediakan Rumah bagi Pekerja</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
