<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeButton - btn back</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeButton</value>
      <webElementGuid>2060c813-70a4-45c4-bb1b-5bbd15b996e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3192e167-e7fc-4a89-b0e9-a75389f0ff08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7b53df0-4d08-48e7-b5ca-5fb745cbb8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>88.0</value>
      <webElementGuid>21c1549b-3ab3-45a0-b6f7-54df200e29ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cabe4f9c-84e2-4023-8ddc-f2f33c519aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>btn back</value>
      <webElementGuid>347c61bb-ac50-4b41-94f4-3cb29a1da718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn back</value>
      <webElementGuid>fb5bdb8a-e2f8-41eb-a0b8-28509c1730eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>86.0</value>
      <webElementGuid>b215b48a-9635-4f42-adda-a0a5b11f8f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>24.0</value>
      <webElementGuid>5bb82b90-bce8-4b9b-80ac-f38a722effad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>96.0</value>
      <webElementGuid>41ede03a-2762-4ee2-a0f6-e065bb82e093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeNavigationBar[1]/XCUIElementTypeButton[1]</value>
      <webElementGuid>71a2e74f-99cf-4f48-83ae-ed6b41ba246f</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeButton' and @label = 'btn back' and @name = 'btn back']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeButton' and @label = 'btn back' and @name = 'btn back']</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeButton</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeButton[`enabled == 1 AND label == 'btn back' AND name == 'btn back'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeButton' AND enabled == 1 AND label == 'btn back' AND name == 'btn back'</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>btn back</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>btn back</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>btn back</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeNavigationBar[1]/XCUIElementTypeButton[1]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
