<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>3c5e57c4-06e3-4da4-ae86-e604502ede74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e20d26af-21a6-4ebe-b039-f9ae515df00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fd8e42c-849d-4f46-80a1-23dff54c18a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>88.0</value>
      <webElementGuid>d103316b-7bd5-48a7-ac05-3755569b45cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5bcf0036-0e09-4f3b-86ef-6caabb457a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      <webElementGuid>44e75b91-21b3-45ed-8e95-ffb6a2535e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      <webElementGuid>1ef2a3cc-be3e-4c9d-ae24-e0a24d408e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      <webElementGuid>8f157947-5003-4f52-ad3d-de6a01fc0661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>684.0</value>
      <webElementGuid>55291368-b2b8-4a02-9786-f1e4cc6b5ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>72.0</value>
      <webElementGuid>6bb26fd5-2539-4ec5-8f33-09c294b2e88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>696.0</value>
      <webElementGuid>2cb8a4a5-5e04-4a48-9ec0-50d44437efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>83a71cda-7782-438d-8a68-02a0d168df72</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' and @name = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' and @value = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' and @name = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' and @value = 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri']</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' AND name == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' AND value == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' AND name == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri' AND name == 'Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri'</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Sasaran Program BPJS Ketenagakerjaan Khusus Buruh Tani di Sumenep Bakal Berubah, Penerima Sebelumnya Harus Bayar Secara Mandiri</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
