<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>16dc0d8e-894b-4e52-a5af-19ead636fbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0fcb799b-3caf-45ae-927c-553e34ff7a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dbc9eb54-026f-4e36-ace1-d2bdc501ef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86.0</value>
      <webElementGuid>d80bdce3-da12-4fe9-9d78-ad2d06030549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bda52c0a-fa17-4231-9647-188f4b34fa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      <webElementGuid>103a5950-c258-4d2b-8a19-4fd9402bda2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      <webElementGuid>9a49d2b4-8140-42f6-a53d-dc6c6544029f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      <webElementGuid>1e26082c-7143-4256-b320-ca3707c12d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>306.0</value>
      <webElementGuid>50051856-1e7d-48af-a9da-9909fe620203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>458.0</value>
      <webElementGuid>d5da7859-2c4b-4c85-8fce-ca22ae127de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1192.0</value>
      <webElementGuid>f7c694a1-a12a-4082-885e-97b6c0e88de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>a648f27e-b9c3-4c33-89b9-3c92c3ea68e5</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' and @name = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' and @value = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' and @name = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' and @value = 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ']</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' AND name == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' AND value == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital '`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' AND name == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital ' AND name == 'Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital '</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Melalui JMO, BPJS Ketenagakerjaan Suguhkan Layanan Digital </value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
