<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeStaticText - Resmi Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeStaticText</value>
      <webElementGuid>f68fea27-36af-4e03-b0f0-90e76c448e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c789cdcc-424c-451b-a809-d8c17ac906f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1e110c1-ed57-4d2c-aded-9f0085255ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>86.0</value>
      <webElementGuid>5faebff6-4591-4537-a58e-104b0a4af123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>94477f48-e66a-4558-ae37-7345517e2be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      <webElementGuid>f4c0794c-6694-4ef2-bf63-cdf90c94b993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      <webElementGuid>ec73f0b3-8ca9-438e-a4de-02a77bc24dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      <webElementGuid>03c50f9a-9ba9-403f-8814-0d8a11868d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>306.0</value>
      <webElementGuid>8af3d275-c81c-4ad8-9037-c27b54b5f45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>458.0</value>
      <webElementGuid>26b4d234-4840-4c4d-a781-6805f84c0ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1192.0</value>
      <webElementGuid>7efb37c3-4a7d-489d-9725-a1a2c2f4d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      <webElementGuid>a6396e8f-fa69-41f5-a192-cd2515e8ce3d</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' and @name = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' and @value = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeStaticText' and @label = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' and @name = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' and @value = 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan']</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeStaticText</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeStaticText[`enabled == 1 AND label == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' AND name == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' AND value == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan'`]</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeStaticText' AND enabled == 1 AND label == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' AND name == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan' AND name == 'Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan'</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeCollectionView[1]/XCUIElementTypeCell[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeStaticText[1]</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>Resmi! Usia Pensiun Pekerja Jadi 59 Tahun untuk Pencairan JP BPJS Ketenagakerjaan</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
